That's scared me again! It's just typo. It's so scary because it won't show in vscode.
ArgumentError: Unknown validator: 'PresenseValidator' (ArgumentError)

            raise ArgumentError, "Unknown validator: '#{key}'"
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
D:/shared/Documents/CPE4254/#4/webForum/app/models/user.rb:9:in `<class:User>'
D:/shared/Documents/CPE4254/#4/webForum/app/models/user.rb:1:in `<main>'