More progress! Now it asks me to set credentials...
PS D:\shared\Documents\CPE4254\#4\webForum> docker run -it -p 127.0.0.1:3000:3000 server:latest
bin/rails aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit` (ArgumentError)

          raise ArgumentError, "Missing `secret_key_base` for '#{Rails.env}' environment, set this string with `bin/rails credentials:edit`"
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/db/config/environment.rb:5:in `<main>'
Tasks: TOP => db:prepare => db:load_config => environment
(See full trace by running task with --trace)
PS D:\shared\Documents\CPE4254\#4\webForum> rails credentials:edit
Configured Git diff driver for credentials.
No $VISUAL or $EDITOR to open file in. Assign one like this:

VISUAL="mate --wait" bin/rails credentials:edit

For editors that fork and exit immediately, it's important to pass a wait flag;
otherwise, the file will be saved immediately with no chance to edit.